#pragma once

enum SDL_MessageBoxColorType
{
	SDL_MESSAGEBOX_COLOR_BACKGROUND = 0,
	SDL_MESSAGEBOX_COLOR_TEXT = 1,
	SDL_MESSAGEBOX_COLOR_BUTTON_BORDER = 2,
	SDL_MESSAGEBOX_COLOR_BUTTON_BACKGROUND = 3,
	SDL_MESSAGEBOX_COLOR_BUTTON_SELECTED = 4,
	SDL_MESSAGEBOX_COLOR_MAX = 5,
};