#pragma once

struct SDL_DisplayMode
{
	unsigned long format; // 0x0
	long w; // 0x4
	long h; // 0x8
	long refresh_rate; // 0xC
	void * driverdata; // 0x10
};
enum SDL_WindowFlags
{
	SDL_WINDOW_FULLSCREEN = 1,
	SDL_WINDOW_OPENGL = 2,
	SDL_WINDOW_SHOWN = 4,
	SDL_WINDOW_HIDDEN = 8,
	SDL_WINDOW_BORDERLESS = 16,
	SDL_WINDOW_RESIZABLE = 32,
	SDL_WINDOW_MINIMIZED = 64,
	SDL_WINDOW_MAXIMIZED = 128,
	SDL_WINDOW_INPUT_GRABBED = 256,
	SDL_WINDOW_INPUT_FOCUS = 512,
	SDL_WINDOW_MOUSE_FOCUS = 1024,
	SDL_WINDOW_FULLSCREEN_DESKTOP = 4097,
	SDL_WINDOW_FOREIGN = 2048,
	SDL_WINDOW_ALLOW_HIGHDPI = 8192,
	SDL_WINDOW_MOUSE_CAPTURE = 16384,
	SDL_WINDOW_ALWAYS_ON_TOP = 32768,
	SDL_WINDOW_SKIP_TASKBAR = 65536,
	SDL_WINDOW_UTILITY = 131072,
	SDL_WINDOW_TOOLTIP = 262144,
	SDL_WINDOW_POPUP_MENU = 524288,
};
enum SDL_WindowEventID
{
	SDL_WINDOWEVENT_NONE = 0,
	SDL_WINDOWEVENT_SHOWN = 1,
	SDL_WINDOWEVENT_HIDDEN = 2,
	SDL_WINDOWEVENT_EXPOSED = 3,
	SDL_WINDOWEVENT_MOVED = 4,
	SDL_WINDOWEVENT_RESIZED = 5,
	SDL_WINDOWEVENT_SIZE_CHANGED = 6,
	SDL_WINDOWEVENT_MINIMIZED = 7,
	SDL_WINDOWEVENT_MAXIMIZED = 8,
	SDL_WINDOWEVENT_RESTORED = 9,
	SDL_WINDOWEVENT_ENTER = 10,
	SDL_WINDOWEVENT_LEAVE = 11,
	SDL_WINDOWEVENT_FOCUS_GAINED = 12,
	SDL_WINDOWEVENT_FOCUS_LOST = 13,
	SDL_WINDOWEVENT_CLOSE = 14,
	SDL_WINDOWEVENT_TAKE_FOCUS = 15,
	SDL_WINDOWEVENT_HIT_TEST = 16,
};
enum SDL_GLattr
{
	SDL_GL_RED_SIZE = 0,
	SDL_GL_GREEN_SIZE = 1,
	SDL_GL_BLUE_SIZE = 2,
	SDL_GL_ALPHA_SIZE = 3,
	SDL_GL_BUFFER_SIZE = 4,
	SDL_GL_DOUBLEBUFFER = 5,
	SDL_GL_DEPTH_SIZE = 6,
	SDL_GL_STENCIL_SIZE = 7,
	SDL_GL_ACCUM_RED_SIZE = 8,
	SDL_GL_ACCUM_GREEN_SIZE = 9,
	SDL_GL_ACCUM_BLUE_SIZE = 10,
	SDL_GL_ACCUM_ALPHA_SIZE = 11,
	SDL_GL_STEREO = 12,
	SDL_GL_MULTISAMPLEBUFFERS = 13,
	SDL_GL_MULTISAMPLESAMPLES = 14,
	SDL_GL_ACCELERATED_VISUAL = 15,
	SDL_GL_RETAINED_BACKING = 16,
	SDL_GL_CONTEXT_MAJOR_VERSION = 17,
	SDL_GL_CONTEXT_MINOR_VERSION = 18,
	SDL_GL_CONTEXT_EGL = 19,
	SDL_GL_CONTEXT_FLAGS = 20,
	SDL_GL_CONTEXT_PROFILE_MASK = 21,
	SDL_GL_SHARE_WITH_CURRENT_CONTEXT = 22,
	SDL_GL_FRAMEBUFFER_SRGB_CAPABLE = 23,
	SDL_GL_CONTEXT_RELEASE_BEHAVIOR = 24,
};
enum SDL_GLprofile
{
	SDL_GL_CONTEXT_PROFILE_CORE = 1,
	SDL_GL_CONTEXT_PROFILE_COMPATIBILITY = 2,
	SDL_GL_CONTEXT_PROFILE_ES = 4,
};