#pragma once

enum EmitterType
{
	PARTICLE_EMITTER = 0,
	CHILD_PARTICLE_EMITTER = 1,
	GPU_PARTICLE_EMITTER = 2,
	LIGHT_EMITTER = 3,
	ALL_EMITTER_TYPE = 4,
};
enum FieldType
{
	TURBULENCE_FIELD = 4,
	ATTRACTION_FIELD = 5,
	TREMOR_FIELD = 6,
	COLLISION_FIELD = 7,
	WIND_FIELD = 8,
	ALL_FIELD_TYPE = 9,
	ALL_EFFECT_TYPE = 9,
};
enum ParticleDialogType
{
	EMITTER_DIALOG = 0,
	GENERATE_DIALOG = 1,
	PARTICLE_DIALOG = 2,
	TEXTURE1_DIALOG = 3,
	TEXTURE2_DIALOG = 4,
	COLOR_DIALOG = 5,
	SCALE_DIALOG = 6,
	ROTATION_DIALOG = 7,
	CHILD_DIALOG = 8,
	ALL_PARTICLE_DIALOG = 9,
};
enum LightDialogType
{
	LIGHT_EMITTER_DIALOG = 0,
	LIGHT_GENERATE_DIALOG = 1,
	LIGHT_PARTICLE_DIALOG = 2,
	LIGHT_COLOR_DIALOG = 3,
	ALL_LIGHT_PARTICLE_DIALOG = 4,
};
enum TurbulenceDialogType
{
	TURBULENCE_DIALOG = 0,
	ALL_TURBULENCE_DIALOG = 1,
};
enum CollisionDialogType
{
	COLLISION_FIELD_DIALOG = 0,
	ALL_COLLISION_DIALOG = 1,
};
enum AttractionDialogType
{
	ATTRACTION_FIELD_DIALOG = 0,
	ALL_ATTRACTION_DIALOG = 1,
};