#pragma once

enum FX::Emitter::GenerationType
{
	POINT = 0,
	EDGE = 1,
	FACE = 2,
};
enum EmitterChartIndex
{
	EMITTER_CHART_SCALE_X = 0,
	EMITTER_CHART_SCALE_Y = 1,
	EMITTER_CHART_SCALE_Z = 2,
	EMITTER_CHART_ROTATE_X = 3,
	EMITTER_CHART_ROTATE_Y = 4,
	EMITTER_CHART_ROTATE_Z = 5,
	EMITTER_CHART_POSITION_X = 6,
	EMITTER_CHART_POSITION_Y = 7,
	EMITTER_CHART_POSITION_Z = 8,
	ALL_EMITTER_CHART_INDEX = 9,
};
enum EmitterEditData
{
	EMITTER_RATIO_TO_FOLLOW = 0,
	EMITTER_SCALE_BASE_X = 1,
	EMITTER_SCALE_BASE_Y = 2,
	EMITTER_SCALE_BASE_Z = 3,
	EMITTER_ROTATE_BASE_X = 4,
	EMITTER_ROTATE_BASE_Y = 5,
	EMITTER_ROTATE_BASE_Z = 6,
	EMITTER_ROTATE_RANDOM_X = 7,
	EMITTER_ROTATE_RANDOM_Y = 8,
	EMITTER_ROTATE_RANDOM_Z = 9,
	EMITTER_POSITION_BASE_X = 10,
	EMITTER_POSITION_BASE_Y = 11,
	EMITTER_POSITION_BASE_Z = 12,
	EMITTER_POSITION_RANDOM_X = 13,
	EMITTER_POSITION_RANDOM_Y = 14,
	EMITTER_POSITION_RANDOM_Z = 15,
	EMITTER_CURVE_SRART_POS = 16,
	EMITTER_CURVE_MOVE_SPEED = 17,
	EMITTER_RATIO_TO_FOLLOW_CAMERA = 18,
	EMITTER_CURVE_RATIO_TO_FOLLOW = 19,
	EMITTER_CURVE_RATIO_TO_FOLLOW_RANDOM = 20,
	ALL_EMITTER_EDIT_INDEX = 21,
};
enum EmitterTextData
{
	EMITTER_STRING_NAME = 0,
	EMITTER_CURVE_PATH = 1,
	EMITTER_MODEL_PATH = 2,
	ALL_EMITTER_TEXT_INDEX = 3,
};
enum EmitterComboIndex
{
	EMITTER_COMBO_EMITTER_TYPE = 0,
	EMITTER_COMBO_SCALE = 1,
	EMITTER_COMBO_ROTATE = 2,
	EMITTER_COMBO_POSITION = 3,
	EMITTER_COMBO_MODEL_GENERATION_TYPE = 4,
	ALL_EMITTER_COMBO_INDEX = 5,
};
enum EmitterTypeIndex
{
	EMITTER_TYPE_POINT = 0,
	EMITTER_TYPE_CUBE = 1,
	EMITTER_TYPE_SPHERE = 2,
	EMITTER_TYPE_CIRCLE = 3,
	EMITTER_TYPE_CURVE = 4,
	EMITTER_TYPE_MODEL = 5,
	ALL_EMITTER_FORM_TYPE = 6,
};
enum EmitterButtonIndex
{
	EMITTER_BUTTON_RATIO_TO_FOLLOW = 0,
	EMITTER_BUTTON_SHOW_EMITTER = 1,
	EMITTER_BUTTON_TIME_ANIMATION_SCALE = 2,
	EMITTER_BUTTON_TIME_ANIMATION_ROTATE = 3,
	EMITTER_BUTTON_TIME_ANIMATION_POSITION = 4,
	EMITTER_CURVE_ROOP = 5,
	EMITTER_BUTTON_RATIO_TO_FOLLOW_CAMERA = 6,
	EMITTER_BUTTON_BLEND_PROJECTION_OFF = 7,
	EMITTER_BUTTON_CURVE_RATIO_TO_FOLLOW_USE = 8,
	ALL_EMITTER_BUTTON_INDEX = 9,
};
enum GenerateChartIndex
{
	GENERATE_CHART_EMIT_VOLUME = 0,
	GENERATE_CHART_DIFFUSE_ALL_DIRECTIONS_VELOCITY = 1,
	GENERATE_CHART_DIFFUSE_ONE_AXIS = 2,
	GENERATE_CHART_SPECIFIED_DIRECTION_VELOCITY_X = 3,
	GENERATE_CHART_SPECIFIED_DIRECTION_VELOCITY_Y = 4,
	GENERATE_CHART_SPECIFIED_DIRECTION_VELOCITY_Z = 5,
	ALL_GENERATE_CHART_INDEX = 6,
};
enum GenerateTextData
{
	ALL_GENERATE_TEXT_INDEX = 0,
};
enum GenerateEditData
{
	GENERATE_START_TIME = 0,
	GENERATE_EMIT_TIME = 1,
	GENERATE_EMIT_VOLUME = 2,
	GENERATE_EMIT_INTERVAL = 3,
	GENERATE_EMIT_INTERVAL_RANDOM = 4,
	GENERATE_DIFFUSE_ALL_DIRECTIONS_VELOCITY = 5,
	GENERATE_DIFFUSE_ALL_DIRECTIONS_VELOCITY_RANDOM = 6,
	GENERATE_DIFFUSE_ONE_AXIS = 7,
	GENERATE_DIFFUSE_ONE_AXIS_RANDOM = 8,
	GENERATE_EMIT_SPECIFIED_DIRECTION_VELOCITY_X = 9,
	GENERATE_EMIT_SPECIFIED_DIRECTION_VELOCITY_Y = 10,
	GENERATE_EMIT_SPECIFIED_DIRECTION_VELOCITY_Z = 11,
	GENERATE_EMIT_SPECIFIED_DIRECTION_VELOCITY_RANDOM_X = 12,
	GENERATE_EMIT_SPECIFIED_DIRECTION_VELOCITY_RANDOM_Y = 13,
	GENERATE_EMIT_SPECIFIED_DIRECTION_VELOCITY_RANDOM_Z = 14,
	GENERATE_ACCELERATION_RESISTANCE = 15,
	GENERATE_ACCELERATION_GRAVITY = 16,
	ALL_GENERATE_EDIT_INDEX = 17,
};
enum GenerateButtonIndexData
{
	GENERATE_INFINITY_EMIT_BUTTON = 0,
	GENERATE_ONE_AXIS_BUTTON = 1,
	GENERATE_ACCELERATION_GRAVITY_BUTTON = 2,
	GENERATE_TIME_ANIMATION_SPECIFIED_DIRECTION_BUTTON = 3,
	GENERATE_TIME_ANIMATION_DIFFUSE_ALL_DIRECTIONS_BUTTON = 4,
	GENERATE_TIME_ANIMATION_DIFFUSE_ONE_AXIS_BUTTON = 5,
	GENERATE_TIME_ANIMATION_EMIT_VOLUME_BUTTON = 6,
	ALL_GENERATE_BUTTON_INDEX = 7,
};
enum GenerateComboIndexData
{
	GENERATE_COMBO_SPECIFIED_DIRECTION = 0,
	ALL_GENERATE_COMBO_INDEX = 1,
};
enum DistortionType
{
	TEXTURE_DISTORTION = 0,
	BACKGROUND_DISTORTION = 1,
	BACKGROUND_DISTORTION_AND_TEXTURE = 2,
	ALL_DISTORTION_TYPE = 3,
};
enum ParticleChartIndex
{
	PARTICLE_CHART_DISTORTION_RATIO = 0,
	ALL_PARTICLE_CHART_INDEX = 1,
};
enum ParticleTextData
{
	PARTICLE_STRING_MODEL_PATH = 0,
	ALL_PARTICLE_TEXT_INDEX = 1,
};
enum ParticleEditData
{
	PARTICLE_LIFE = 0,
	PARTICLE_LIFE_RANDOM = 1,
	PARTICLE_CENTER_X = 2,
	PARTICLE_CENTER_Y = 3,
	PARTICLE_CAMERA_OFFSET = 4,
	PARTICLE_STRIPE_INTERPOLATION_NUM = 5,
	PARTICLE_STRIPE_TENSION = 6,
	PARTICLE_STRIPE_BIAS = 7,
	PARTICLE_STRIPE_CONTINUITY = 8,
	PARTICLE_EDIT_DISTORTION_RATIO = 9,
	PARTICLE_EDIT_DUMMY = 10,
	PARTICLE_EDIT_FALLOFF_OPACITY = 11,
	PARTICLE_EDIT_INFLUENCE_OF_LIGHT = 12,
	PARTICLE_EDIT_INFLUENCE_OF_SHADOW = 13,
	ALL_PARTICLE_EDIT_INDEX = 14,
};
enum ParticleComboData
{
	PARTICLE_COMBO_PARTICLE_TYPE = 0,
	PARTICLE_COMBO_STRIPE_INTERPOLATION_TYPE = 1,
	PARTICLE_COMBO_BLUR_BIND_BONE_1 = 2,
	PARTICLE_COMBO_BLUR_BIND_BONE_2 = 3,
	PARTICLE_COMBO_MODEL_BILLBOARD_TYPE = 4,
	PARTICLE_COMBO_DISTORTION_TARGET = 5,
	PARTICLE_COMBO_FALLOFF_TYPE = 6,
	PARTICLE_COMBO_BLEND_STATE = 7,
	PARTICLE_COMBO_CULL_MODE = 8,
	ALL_PARTICLE_COMBO_INDEX = 9,
};
enum ParticleButtonData
{
	PARTICLE_BUTTON_LIFE_UNLIMITED = 0,
	PARTICLE_BUTTON_PLANE_TYPE = 1,
	PARTICLE_BUTTON_AXIS_BILLBOARD_TYPE = 1,
	PARTICLE_BUTTON_FIGURE_BILLBOARD_DUMMY = 2,
	PARTICLE_BUTTON_Z_SORT = 3,
	PARTICLE_BUTTON_STRIPE_TYPE = 4,
	PARTICLE_BUTTON_STRIPE_WHETHER_AXIS_BILLBOARD_IS_USE = 5,
	PARTICLE_BUTTON_IGNORE_ACTION_ROTATE = 6,
	PARTICLE_BUTTON_BLUR_ON = 7,
	PARTICLE_BUTTON_DISTORTION_USE = 8,
	PARTICLE_BUTTON_FALLOFF_USE = 9,
	PARTICLE_BUTTON_DISTORTION_TIME_ANIMATION = 10,
	PARTICLE_BUTTON_DEPTH_WRITE_MASK = 11,
	PARTICLE_BUTTON_LIT = 12,
	PARTICLE_BUTTON_FOG = 13,
	PARTICLE_BUTTON_BLOOM = 14,
	PARTICLE_BUTTON_IGNORE_UV_MIRROR = 15,
	ALL_PARTICLE_BUTTON_INDEX = 16,
};
enum ParticleType
{
	PARTICLE_TYPE_PLANE = 0,
	PARTICLE_TYPE_BILLBOARD = 1,
	PARTICLE_TYPE_ONE_AXIS_BILLBOARD = 2,
	PARTICLE_TYPE_DIRECTIONAL = 3,
	PARTICLE_TYPE_FIGURE = 4,
	PARTICLE_TYPE_STRIPE = 5,
	PARTICLE_TYPE_DUMMY = 6,
	PARTICLE_TYPE_GPU_PARTICLE = 7,
	ALL_PARTICLE_TYPE = 8,
};
enum ParticlePlaneType
{
	XY_PLANE = 0,
	XZ_PLANE = 1,
	YZ_PLANE = 2,
};
enum ParticleStripeType
{
	STRIPE_TYPE_RIBBON = 0,
	STRIPE_TYPE_CROSS = 1,
};
enum TextureChartIndex
{
	ALL_TEXTURE1_CHART_INDEX = 0,
};
enum TextureStringData
{
	TEX_STRING_COLOR_TEX_DATA_PATH = 0,
	TEX_STRING_NORMAL_TEX_DATA_PATH = 1,
	TEX_STRING_ALPHA_TEX_DATA_PATH = 2,
	ALL_TEX_TEXT_INDEX = 3,
};
enum TextureEditData
{
	TEX_EDIT_COLOR_H_DEVIDE_NUM = 0,
	TEX_EDIT_COLOR_V_DEVIDE_NUM = 1,
	TEX_EDIT_COLOR_ANIME_SIZE = 2,
	TEX_EDIT_COLOR_ANIME_SPEED = 3,
	TEX_EDIT_COLOR_UV_V_SCROLL = 4,
	TEX_EDIT_COLOR_UV_H_SCROLL = 5,
	TEX_EDIT_COLOR_UV_ROTATE = 6,
	TEX_EDIT_NORMAL_H_DEVIDE_NUM = 7,
	TEX_EDIT_NORMAL_V_DEVIDE_NUM = 8,
	TEX_EDIT_NORMAL_ANIME_SIZE = 9,
	TEX_EDIT_NORMAL_ANIME_SPEED = 10,
	TEX_EDIT_NORMAL_UV_V_SCROLL = 11,
	TEX_EDIT_NORMAL_UV_H_SCROLL = 12,
	TEX_EDIT_NORMAL_UV_ROTATE = 13,
	TEX_EDIT_ALPHA_H_DEVIDE_NUM = 14,
	TEX_EDIT_ALPHA_V_DEVIDE_NUM = 15,
	TEX_EDIT_ALPHA_ANIME_SIZE = 16,
	TEX_EDIT_ALPHA_ANIME_SPEED = 17,
	TEX_EDIT_ALPHA_UV_V_SCROLL = 18,
	TEX_EDIT_ALPHA_UV_H_SCROLL = 19,
	TEX_EDIT_ALPHA_UV_ROTATE = 20,
	ALL_TEX_EDIT_INDEX = 21,
};
enum TextureButtonData
{
	TEX_BUTTON_COLOR_RANDOM_CHECK_BOX = 0,
	TEX_BUTTON_NORMAL_RANDOM_CHECK_BOX = 1,
	TEX_BUTTON_ALPHA_RANDOM_CHECK_BOX = 2,
	TEX_BUTTON_COLOR_TEXTURE_USE = 3,
	TEX_BUTTON_NORMAL_TEXTURE_USE = 4,
	TEX_BUTTON_ALPHA_TEXTURE_USE = 5,
	ALL_TEX_BUTTON_INDEX = 6,
};
enum TextureComboData
{
	TEX_COMBO_COLOR_ANIME_PLAY_METHOD = 0,
	TEX_COMBO_COLOR_UV_MAP_METHOD = 1,
	TEX_COMBO_NORMAL_ANIME_PLAY_METHOD = 2,
	TEX_COMBO_NORMAL_UV_MAP_METHOD = 3,
	TEX_COMBO_ALPHA_ANIME_PLAY_METHOD = 4,
	TEX_COMBO_ALPHA_UV_MAP_METHOD = 5,
	ALL_TEX_COMBO_INDEX = 6,
};
enum BlendStateType
{
	ALPHA = 0,
	ALPHA_COVERAGE = 1,
	HALF_ADD = 2,
	HALF_SUBTRACT = 3,
	ADD = 4,
	TESTADD = 5,
	SUBTRACT = 6,
	DEFAULT = 7,
	MAX_BLEND_STATE = 8,
};
enum Texture2ChartIndex
{
	ALL_TEXTURE2_CHART_INDEX = 0,
};
enum Texture2StringData
{
	TEX2_STRING_COLOR_TEX_DATA_PATH = 0,
	TEX2_STRING_ALPHA_TEX_DATA_PATH = 1,
	ALL_TEX2_TEXT_INDEX = 2,
};
enum Texture2EditData
{
	TEX2_EDIT_COLOR_H_DEVIDE_NUM = 0,
	TEX2_EDIT_COLOR_V_DEVIDE_NUM = 1,
	TEX2_EDIT_COLOR_ANIME_SIZE = 2,
	TEX2_EDIT_COLOR_ANIME_SPEED = 3,
	TEX2_EDIT_COLOR_UV_V_SCROLL = 4,
	TEX2_EDIT_COLOR_UV_H_SCROLL = 5,
	TEX2_EDIT_COLOR_UV_ROTATE = 6,
	TEX2_EDIT_ALPHA_H_DEVIDE_NUM = 7,
	TEX2_EDIT_ALPHA_V_DEVIDE_NUM = 8,
	TEX2_EDIT_ALPHA_ANIME_SIZE = 9,
	TEX2_EDIT_ALPHA_ANIME_SPEED = 10,
	TEX2_EDIT_ALPHA_UV_V_SCROLL = 11,
	TEX2_EDIT_ALPHA_UV_H_SCROLL = 12,
	TEX2_EDIT_ALPHA_UV_ROTATE = 13,
	ALL_TEX2_EDIT_INDEX = 14,
};
enum Texture2ButtonData
{
	TEX2_BUTTON_COLOR_RANDOM_CHECK_BOX = 0,
	TEX2_BUTTON_ALPHA_RANDOM_CHECK_BOX = 1,
	TEX2_BUTTON_COLOR_TEXTURE_USE = 2,
	TEX2_BUTTON_ALPHA_TEXTURE_USE = 3,
	ALL_TEX2_BUTTON_INDEX = 4,
};
enum Texture2ComboData
{
	TEX2_COMBO_COLOR_ANIME_PLAY_METHOD = 0,
	TEX2_COMBO_COLOR_UV_MAP_METHOD = 1,
	TEX2_COMBO_ALPHA_ANIME_PLAY_METHOD = 2,
	TEX2_COMBO_ALPHA_UV_MAP_METHOD = 3,
	TEX2_COMBO_MULTI_TEXTURE_BLEND_TYPE = 4,
	ALL_TEX2_COMBO_INDEX = 5,
};
enum ColorChartIndex
{
	COLOR_CHART_R = 0,
	COLOR_CHART_G = 1,
	COLOR_CHART_B = 2,
	COLOR_CHART_A = 3,
	ALL_COLOR_CHART_INDEX = 4,
};
enum ColorTextData
{
	ALL_COLOR_TEXT_INDEX = 0,
};
enum ColorEditData
{
	COLOR_R = 0,
	COLOR_G = 1,
	COLOR_B = 2,
	COLOR_A = 3,
	ALL_COLOR_EDIT_INDEX = 4,
};
enum ColorComboData
{
	ALL_COLOR_COMBO_INDEX = 0,
};
enum ColorButtonIndex
{
	COLOR_BUTTON_TIME_ANIMATION = 0,
	ALL_COLOR_BUTTON_INDEX = 1,
};
enum ScaleChartIndex
{
	SCALE_CHART_VELOCITY_X = 0,
	SCALE_CHART_VELOCITY_Y = 1,
	SCALE_CHART_VELOCITY_Z = 2,
	SCALE_CHART_DEFAULT_X = 3,
	SCALE_CHART_DEFAULT_Y = 4,
	SCALE_CHART_DEFAULT_Z = 5,
	ALL_SCALE_CHART_INDEX = 6,
};
enum ScaleTextData
{
	ALL_SCALE_TEXT_INDEX = 0,
};
enum ScaleEditData
{
	SCALE_DEFAULT_X = 0,
	SCALE_DEFAULT_Y = 1,
	SCALE_DEFAULT_Z = 2,
	SCALE_DEFAULT_RANDOM_X = 3,
	SCALE_DEFAULT_RANDOM_Y = 4,
	SCALE_DEFAULT_RANDOM_Z = 5,
	SCALE_VELOCITY_X = 6,
	SCALE_VELOCITY_Y = 7,
	SCALE_VELOCITY_Z = 8,
	SCALE_VELOCITY_RANDOM_X = 9,
	SCALE_VELOCITY_RANDOM_Y = 10,
	SCALE_VELOCITY_RANDOM_Z = 11,
	SCALE_ACCELERATION_X = 12,
	SCALE_ACCELERATION_Y = 13,
	SCALE_ACCELERATION_Z = 14,
	SCALE_ACCELERATION_RANDOM_X = 15,
	SCALE_ACCELERATION_RANDOM_Y = 16,
	SCALE_ACCELERATION_RANDOM_Z = 17,
	ALL_SCALE_EDIT_INDEX = 18,
};
enum ScaleComboData
{
	SCALE_COMBO_DEFAULT = 0,
	SCALE_COMBO_VELOCITY = 1,
	SCALE_COMBO_ACCELERATION = 2,
	ALL_SCALE_COMBO_INDEX = 3,
};
enum ScaleButtonIndex
{
	SCALE_BUTTON_TIME_ANIMATION = 0,
	SCALE_BUTTON_DEFFAULT_TIME_ANIMATION = 1,
	ALL_SCALE_BUTTON_INDEX = 2,
};
enum RotateChartIndex
{
	ROTATE_CHART_VELOCITY_X = 0,
	ROTATE_CHART_VELOCITY_Y = 1,
	ROTATE_CHART_VELOCITY_Z = 2,
	ALL_ROTATE_CHART_INDEX = 3,
};
enum RotationTextData
{
	ALL_ROTATE_TEXT_INDEX = 0,
};
enum RotationEditData
{
	ROTATE_DEFAULT_X = 0,
	ROTATE_DEFAULT_Y = 1,
	ROTATE_DEFAULT_Z = 2,
	ROTATE_DEFAULT_RANDOM_X = 3,
	ROTATE_DEFAULT_RANDOM_Y = 4,
	ROTATE_DEFAULT_RANDOM_Z = 5,
	ROTATE_VELOCITY_X = 6,
	ROTATE_VELOCITY_Y = 7,
	ROTATE_VELOCITY_Z = 8,
	ROTATE_VELOCITY_RANDOM_X = 9,
	ROTATE_VELOCITY_RANDOM_Y = 10,
	ROTATE_VELOCITY_RANDOM_Z = 11,
	ROTATE_ACCELERATION_X = 12,
	ROTATE_ACCELERATION_Y = 13,
	ROTATE_ACCELERATION_Z = 14,
	ROTATE_ACCELERATION_RANDOM_X = 15,
	ROTATE_ACCELERATION_RANDOM_Y = 16,
	ROTATE_ACCELERATION_RANDOM_Z = 17,
	ROTATE_ATTENUATION = 18,
	ALL_ROTATE_EDIT_INDEX = 19,
};
enum RotationComboData
{
	ROTATE_COMBO_DEFAULT = 0,
	ROTATE_COMBO_VELOCITY = 1,
	ROTATE_COMBO_ACCELERATION = 2,
	ALL_ROTATE_COMBO_INDEX = 3,
};
enum RotateButtonIndex
{
	ROTATE_BUTTON_TIME_ANIMATION = 0,
	ALL_ROTATE_BUTTON_INDEX = 1,
};
enum ChildChartIndex
{
	ALL_CHILD_CHART_INDEX = 0,
};
enum ChildButtonIndex
{
	CHILD_BUTTON_INHERITANCE_SCALE = 0,
	CHILD_BUTTON_INHERITANCE_ROTATE = 1,
	CHILD_BUTTON_INHERITANCE_ACCELERATION = 2,
	ALL_CHILD_BUTTON_INDEX = 3,
};
enum ChildEditIndex
{
	CHILD_GENERATE_TIMING = 0,
	CHILD_RATIO_TO_FOLLOW = 1,
	CHILD_RATIO_TO_FOLLOW_RANDOM = 2,
	CHILD_INHERITANCE_VELOCITY = 3,
	CHILD_INHERITANCE_VELOCITY_RANDOM = 4,
	CHILD_INHERITANCE_COLOR = 5,
	CHILD_INHERITANCE_COLOR_RANDOM = 6,
	ALL_CHILD_EDIT_INDEX = 7,
};
enum GPUPartilceParticleTextIndex
{
	ALL_GPU_PARTICLE_PARTICLE_TEXT_INDEX = 0,
};
enum GPUParticleParticleComboIndex
{
	ALL_GPU_PARTICLE_PARTICLE_COMBO_INDEX = 0,
};
enum GPUParticleParticleButtonIndex
{
	GPU_PARTICLE_PARTICLE_LIFE_UNLIMITED = 0,
	ALL_GPU_PARTICLE_PARTICLE_BUTTON_INDEX = 1,
};
enum GPUParticleParticleEditIndex
{
	GPU_PARTICLE_PARTICLE_LIFE = 0,
	GPU_PARTICLE_PARTICLE_LIFE_RANDOM = 1,
	ALL_GPU_PARTICLE_PARTICLE_EDIT_INDEX = 2,
};
enum GPUPartilceTextureTextIndex
{
	ALL_GPU_PARTICLE_TEXTURE_TEXT_INDEX = 0,
};
enum GPUParticleTextureComboIndex
{
	GPU_PARTICLE_TEXTURE_COMBO_ANIME_PLAY_METHOD = 0,
	ALL_GPU_PARTICLE_TEXTURE_COMBO_INDEX = 1,
};
enum GPUParticleTextureButtonIndex
{
	ALL_GPU_PARTICLE_TEXTURE_BUTTON_INDEX = 0,
};
enum GPUParticleTextureEditIndex
{
	GPU_PARTICLE_TEXTURE_EDIT_COLOR_H_DEVIDE_NUM = 0,
	GPU_PARTICLE_TEXTURE_EDIT_COLOR_V_DEVIDE_NUM = 1,
	GPU_PARTICLE_TEXTURE_EDIT_COLOR_TEXTURE_NUM = 2,
	GPU_PARTICLE_TEXTURE_EDIT_COLOR_ANIME_PARAM = 3,
	ALL_GPU_PARTICLE_TEXTURE_EDIT_INDEX = 4,
};
enum LightEmitterChartIndex
{
	ALL_LIGHT_EMITTER_CHART_INDEX = 0,
};
enum LightEmitterEditData
{
	LIGHT_EMITTER_ROTATE_BASE_X = 0,
	LIGHT_EMITTER_ROTATE_BASE_Y = 1,
	LIGHT_EMITTER_ROTATE_BASE_Z = 2,
	LIGHT_EMITTER_POSITION_BASE_X = 3,
	LIGHT_EMITTER_POSITION_BASE_Y = 4,
	LIGHT_EMITTER_POSITION_BASE_Z = 5,
	ALL_LIGHT_EMITTER_EDIT_INDEX = 6,
};
enum LightEmitterTextData
{
	LIGHT_EMITTER_STRING_NAME = 0,
	ALL_LIGHT_EMITTER_TEXT_INDEX = 1,
};
enum LightEmitterComboIndex
{
	LIGHT_EMITTER_COMBO_ROTATE = 0,
	LIGHT_EMITTER_COMBO_POSITION = 1,
	ALL_LIGHT_EMITTER_COMBO_INDEX = 2,
};
enum LightEmitterButtonIndex
{
	ALL_LIGHT_EMITTER_BUTTON_INDEX = 0,
};
enum LightParticleChartIndex
{
	LIGHT_PARTICLE_CHART_INTENSITY = 0,
	ALL_LIGHT_PARTICLE_CHART_INDEX = 1,
};
enum LightParticleTextData
{
	ALL_LIGHT_PARTICLE_TEXT_INDEX = 0,
};
enum LightParticleEditData
{
	LIGHT_PARTICLE_LIFE = 0,
	LIGHT_PARTICLE_LIGHT_INTENSITY = 1,
	LIGHT_PARTICLE_SPOT_CONE_ANGLE = 2,
	LIGHT_PARTICLE_SPOT_PENUMBRA = 3,
	ALL_LIGHT_PARTICLE_EDIT_INDEX = 4,
};
enum LightParticleComboData
{
	LIGHT_PARTICLE_COMBO_LIGHT_TYPE = 0,
	LIGHT_PARTICLE_COMBO_DECAY_TYPE = 1,
	ALL_LIGHT_PARTICLE_COMBO_INDEX = 2,
};
enum LightParticleButtonData
{
	LIGHT_PARTICLE_BUTTON_TIME_ANIMATION_INTENSITY = 0,
	LIGHT_PARTICLE_BUTTON_USE_SPECULAR = 1,
	LIGHT_PARTICLE_BUTTON_USE_DIFFUSE = 2,
	ALL_LIGHT_PARTICLE_BUTTON_INDEX = 3,
};
enum TurbulenceEditIndex
{
	TURBULENCE_POS_X = 0,
	TURBULENCE_POS_Y = 1,
	TURBULENCE_POS_Z = 2,
	TURBULENCE_CENTRAL_ROT_X = 3,
	TURBULENCE_CENTRAL_ROT_Y = 4,
	TURBULENCE_CENTRAL_ROT_Z = 5,
	TURBULENCE_SURFACE_ROT_X = 6,
	TURBULENCE_SURFACE_ROT_Y = 7,
	TURBULENCE_SURFACE_ROT_Z = 8,
	TURBULENCE_RANGE = 9,
	ALL_TURBULENCE_EDIT_INDEX = 10,
};
enum TurbulenceComboIndex
{
	TURBULENCE_COMBO_POS = 0,
	TURBULENCE_COMBO_CENTRAL_ROT = 1,
	TURBULENCE_COMBO_SURFACE_ROT = 2,
	ALL_TURBULENCE_COMBO_INDEX = 3,
};
enum TurbulenceButtonIndex
{
	TURBULENCE_BUTTON_TIME_ANIMATION_CENTRAL_ROT = 0,
	TURBULENCE_BUTTON_TIME_ANIMATION_SURFACE_ROT = 1,
	TURBULENCE_BUTTON_TIME_ANIMATION_RANGE = 2,
	ALL_TURBULENCE_BUTTON_INDEX = 3,
};
enum CollisionFieldChartIndex
{
	COLLISION_CHART_SCALE_X = 0,
	COLLISION_CHART_SCALE_Y = 1,
	COLLISION_CHART_SCALE_Z = 2,
	ALL_COLLISION_CHART_INDEX = 3,
};
enum CollisionFieldTextData
{
	COLLISION_TEXT_NAME = 0,
	ALL_COLLISION_TEXT_INDEX = 1,
};
enum CollisionFieldEditIndex
{
	COLLISION_EDIT_SCALE_X = 0,
	COLLISION_EDIT_SCALE_Y = 1,
	COLLISION_EDIT_SCALE_Z = 2,
	COLLISION_EDIT_ROTATE_X = 3,
	COLLISION_EDIT_ROTATE_Y = 4,
	COLLISION_EDIT_ROTATE_Z = 5,
	COLLISION_EDIT_POSITION_X = 6,
	COLLISION_EDIT_POSITION_Y = 7,
	COLLISION_EDIT_POSITION_Z = 8,
	COLLISION_EDIT_VELOCITY_ATTENUATION_RATE_X = 9,
	COLLISION_EDIT_VELOCITY_ATTENUATION_RATE_Y = 10,
	COLLISION_EDIT_VELOCITY_ATTENUATION_RATE_Z = 11,
	COLLISION_EDIT_VELOCITY_ATTENUATION_RATE_RANDOM_X = 12,
	COLLISION_EDIT_VELOCITY_ATTENUATION_RATE_RANDOM_Y = 13,
	COLLISION_EDIT_VELOCITY_ATTENUATION_RATE_RANDOM_Z = 14,
	COLLISION_EDIT_ROTATE_ATTENUATION_RATE_X = 15,
	COLLISION_EDIT_ROTATE_ATTENUATION_RATE_Y = 16,
	COLLISION_EDIT_ROTATE_ATTENUATION_RATE_Z = 17,
	COLLISION_EDIT_ROTATE_ATTENUATION_RATE_RANDOM_X = 18,
	COLLISION_EDIT_ROTATE_ATTENUATION_RATE_RANDOM_Y = 19,
	COLLISION_EDIT_ROTATE_ATTENUATION_RATE_RANDOM_Z = 20,
	ALL_COLLISION_EDIT_INDEX = 21,
};
enum CollisionFieldComboIndex
{
	COLLISION_COMBO_FORM_TYPE = 0,
	COLLISION_COMBO_SCALE = 1,
	COLLISION_COMBO_ROTATE = 2,
	COLLISION_COMBO_POSITION = 3,
	COLLISION_COMBO_COLLISION_BEHAVIOR = 4,
	COLLISION_COMBO_VELOCITY_ATTENUATION_RATE = 5,
	COLLISION_COMBO_ROTATE_ATTENUATION_RATE = 6,
	ALL_COLLISION_COMBO_INDEX = 7,
};
enum CollisionFieldButtonIndex
{
	COLLISION_BUTTON_FLAT_TYPE = 0,
	COLLISION_BUTTON_SCALE_TIME_ANIME_USE = 1,
	COLLISION_BUTTON_POSITION_COORDINATE_SPACE = 2,
	ALL_COLLISION_BUTTON_INDEX = 3,
};
enum FX::Collision::FormType
{
	PLANE = 0,
	CUBE = 1,
	SPHERE = 2,
	MODEL = 3,
};
enum FX::Collision::Behavior
{
	REFRECT = 0,
	KILL = 1,
	MOVE = 2,
	CHILD = 3,
};
enum AttractionFieldChartIndex
{
	ATTRACTION_CHART_SCALE_X = 0,
	ATTRACTION_CHART_SCALE_Y = 1,
	ATTRACTION_CHART_SCALE_Z = 2,
	ATTRACTION_CHART_ATTRACTION_ACCELERATION = 3,
	ATTRACTION_CHART_ATTRACTION_RANGE = 4,
	ALL_ATTRACTION_CHART_INDEX = 5,
};
enum AttractionFieldTextData
{
	ATTRACTION_TEXT_NAME = 0,
	ALL_ATTRACTION_TEXT_INDEX = 1,
};
enum AttractionFieldEditIndex
{
	ATTRACTION_EDIT_SCALE_X = 0,
	ATTRACTION_EDIT_SCALE_Y = 1,
	ATTRACTION_EDIT_SCALE_Z = 2,
	ATTRACTION_EDIT_ROTATE_X = 3,
	ATTRACTION_EDIT_ROTATE_Y = 4,
	ATTRACTION_EDIT_ROTATE_Z = 5,
	ATTRACTION_EDIT_POSITION_X = 6,
	ATTRACTION_EDIT_POSITION_Y = 7,
	ATTRACTION_EDIT_POSITION_Z = 8,
	ATTRACTION_EDIT_ATTRACTION_VELOCITY = 9,
	ATTRACTION_EDIT_ATTRACTION_ACCELERATION = 10,
	ATTRACTION_EDIT_FIELD_RANGE = 11,
	ALL_ATTRACTION_EDIT_INDEX = 12,
};
enum AttractionFieldComboIndex
{
	ATTRACTION_COMBO_FORM_TYPE = 0,
	ATTRACTION_COMBO_SCALE = 1,
	ATTRACTION_COMBO_ROTATE = 2,
	ATTRACTION_COMBO_POSITION = 3,
	ALL_ATTRACTION_COMBO_INDEX = 4,
};
enum AttractionFieldButtonIndex
{
	ATTRACTION_BUTTON_SCALE_TIME_ANIME_USE = 0,
	ATTRACTION_BUTTON_ACCELERATION_TIME_ANIME_USE = 1,
	ATTRACTION_BUTTON_RANGE_TIME_ANIME_USE = 2,
	ALL_ATTRACTION_BUTTON_INDEX = 3,
};