#pragma once

bool Scaleform::Alg::OperatorLess<Scaleform::GFx::AS3::Instances::fl_display::MovieClip::FrameScript::Descr>::Compare(const Scaleform::GFx::AS3::Instances::fl_display::MovieClip::FrameScript::Descr & a, const Scaleform::GFx::AS3::Instances::fl_display::MovieClip::FrameScript::Descr & b); // 0x140576260
void Scaleform::Alg::QuickSortSliced<Scaleform::ArrayPagedPOD<Scaleform::GFx::FontCompactor::KerningPairType,6,64,261>,bool (__cdecl*)(Scaleform::GFx::FontCompactor::KerningPairType const & __ptr64,Scaleform::GFx::FontCompactor::KerningPairType const & __ptr64)>(Scaleform::ArrayPagedPOD<Scaleform::GFx::FontCompactor::KerningPairType,6,64,261> & arr, unsigned long long start, unsigned long long end, bool(*less)(const Scaleform::GFx::FontCompactor::KerningPairType &, const Scaleform::GFx::FontCompactor::KerningPairType &)); // 0x1404221B0
void Scaleform::Alg::QuickSortSliced<Scaleform::ArrayDH<Scaleform::Ptr<Scaleform::GFx::InteractiveObject>,327,Scaleform::ArrayDefaultPolicy>,Scaleform::GFx::AutoTabSortFunctor>(Scaleform::ArrayDH<Scaleform::Ptr<Scaleform::GFx::InteractiveObject>,327,Scaleform::ArrayDefaultPolicy> & arr, unsigned long long start, unsigned long long end, Scaleform::GFx::AutoTabSortFunctor less); // 0x1402DB5A0
void Scaleform::Alg::QuickSortSliced<Scaleform::ArrayDH<Scaleform::Ptr<Scaleform::GFx::InteractiveObject>,327,Scaleform::ArrayDefaultPolicy>,Scaleform::GFx::TabIndexSortFunctor>(Scaleform::ArrayDH<Scaleform::Ptr<Scaleform::GFx::InteractiveObject>,327,Scaleform::ArrayDefaultPolicy> & arr, unsigned long long start, unsigned long long end, Scaleform::GFx::TabIndexSortFunctor less); // 0x1402DBA70
void Scaleform::Alg::QuickSortSliced<Scaleform::Render::ArrayPaged<unsigned int,4,16>,Scaleform::Render::Hairliner::CmpScanbeams>(Scaleform::Render::ArrayPaged<unsigned int,4,16> & arr, unsigned long long start, unsigned long long end, Scaleform::Render::Hairliner::CmpScanbeams less); // 0x1403B85F0
void Scaleform::Alg::QuickSortSliced<Scaleform::Render::ArrayPaged<Scaleform::Render::Hairliner::MonoChainType * __ptr64,4,8>,bool (__cdecl*)(Scaleform::Render::Hairliner::MonoChainType const * __ptr64,Scaleform::Render::Hairliner::MonoChainType const * __ptr64)>(Scaleform::Render::ArrayPaged<Scaleform::Render::Hairliner::MonoChainType *,4,8> & arr, unsigned long long start, unsigned long long end, bool(*less)(const Scaleform::Render::Hairliner::MonoChainType *, const Scaleform::Render::Hairliner::MonoChainType *)); // 0x1403B8B20
void Scaleform::Alg::QuickSortSliced<Scaleform::Render::ArrayPaged<Scaleform::Render::Hairliner::FanEdgeType,4,16>,bool (__cdecl*)(Scaleform::Render::Hairliner::FanEdgeType const & __ptr64,Scaleform::Render::Hairliner::FanEdgeType const & __ptr64)>(Scaleform::Render::ArrayPaged<Scaleform::Render::Hairliner::FanEdgeType,4,16> & arr, unsigned long long start, unsigned long long end, bool(*less)(const Scaleform::Render::Hairliner::FanEdgeType &, const Scaleform::Render::Hairliner::FanEdgeType &)); // 0x1403B8F70
void Scaleform::Alg::QuickSortSliced<Scaleform::Render::ArrayPaged<Scaleform::Render::Hairliner::HorizontalEdgeType,2,4>,bool (__cdecl*)(Scaleform::Render::Hairliner::HorizontalEdgeType const & __ptr64,Scaleform::Render::Hairliner::HorizontalEdgeType const & __ptr64)>(Scaleform::Render::ArrayPaged<Scaleform::Render::Hairliner::HorizontalEdgeType,2,4> & arr, unsigned long long start, unsigned long long end, bool(*less)(const Scaleform::Render::Hairliner::HorizontalEdgeType &, const Scaleform::Render::Hairliner::HorizontalEdgeType &)); // 0x1403B9470
void Scaleform::Alg::QuickSortSliced<Scaleform::Alg::ArrayAdaptor<Scaleform::Render::Rasterizer::Cell * __ptr64>,bool (__cdecl*)(Scaleform::Render::Rasterizer::Cell const * __ptr64,Scaleform::Render::Rasterizer::Cell const * __ptr64)>(Scaleform::Alg::ArrayAdaptor<Scaleform::Render::Rasterizer::Cell *> & arr, unsigned long long start, unsigned long long end, bool(*less)(const Scaleform::Render::Rasterizer::Cell *, const Scaleform::Render::Rasterizer::Cell *)); // 0x140408B40
void Scaleform::Alg::QuickSortSliced<Scaleform::ArrayPagedLH_POD<Scaleform::Render::RectPacker::RectType,8,64,2>,bool (__cdecl*)(Scaleform::Render::RectPacker::RectType const & __ptr64,Scaleform::Render::RectPacker::RectType const & __ptr64)>(Scaleform::ArrayPagedLH_POD<Scaleform::Render::RectPacker::RectType,8,64,2> & arr, unsigned long long start, unsigned long long end, bool(*less)(const Scaleform::Render::RectPacker::RectType &, const Scaleform::Render::RectPacker::RectType &)); // 0x1404286D0
void Scaleform::Alg::QuickSortSliced<Scaleform::ArrayStaticBuffPOD<Scaleform::Render::Scale9GridTess::TmpVertexType,72,2>,bool (__cdecl*)(Scaleform::Render::Scale9GridTess::TmpVertexType const & __ptr64,Scaleform::Render::Scale9GridTess::TmpVertexType const & __ptr64)>(Scaleform::ArrayStaticBuffPOD<Scaleform::Render::Scale9GridTess::TmpVertexType,72,2> & arr, unsigned long long start, unsigned long long end, bool(*less)(const Scaleform::Render::Scale9GridTess::TmpVertexType &, const Scaleform::Render::Scale9GridTess::TmpVertexType &)); // 0x1403C96A0
void Scaleform::Alg::QuickSortSliced<Scaleform::Render::ArrayUnsafe<Scaleform::Render::StrokeSorter::SortedPathType>,bool (__cdecl*)(Scaleform::Render::StrokeSorter::SortedPathType const & __ptr64,Scaleform::Render::StrokeSorter::SortedPathType const & __ptr64)>(Scaleform::Render::ArrayUnsafe<Scaleform::Render::StrokeSorter::SortedPathType> & arr, unsigned long long start, unsigned long long end, bool(*less)(const Scaleform::Render::StrokeSorter::SortedPathType &, const Scaleform::Render::StrokeSorter::SortedPathType &)); // 0x14039DF40
void Scaleform::Alg::QuickSortSliced<Scaleform::Render::ArrayPaged<unsigned int,4,16>,Scaleform::Render::Tessellator::CmpScanbeams>(Scaleform::Render::ArrayPaged<unsigned int,4,16> & arr, unsigned long long start, unsigned long long end, Scaleform::Render::Tessellator::CmpScanbeams less); // 0x1403B85F0
void Scaleform::Alg::QuickSortSliced<Scaleform::Render::ArrayPaged<Scaleform::Render::Tessellator::OuterEdgeType,4,16>,bool (__cdecl*)(Scaleform::Render::Tessellator::OuterEdgeType const & __ptr64,Scaleform::Render::Tessellator::OuterEdgeType const & __ptr64)>(Scaleform::Render::ArrayPaged<Scaleform::Render::Tessellator::OuterEdgeType,4,16> & arr, unsigned long long start, unsigned long long end, bool(*less)(const Scaleform::Render::Tessellator::OuterEdgeType &, const Scaleform::Render::Tessellator::OuterEdgeType &)); // 0x1403A1650
void Scaleform::Alg::QuickSortSliced<Scaleform::Render::ArrayPaged<Scaleform::Render::Tessellator::StrokerEdgeType,4,16>,bool (__cdecl*)(Scaleform::Render::Tessellator::StrokerEdgeType const & __ptr64,Scaleform::Render::Tessellator::StrokerEdgeType const & __ptr64)>(Scaleform::Render::ArrayPaged<Scaleform::Render::Tessellator::StrokerEdgeType,4,16> & arr, unsigned long long start, unsigned long long end, bool(*less)(const Scaleform::Render::Tessellator::StrokerEdgeType &, const Scaleform::Render::Tessellator::StrokerEdgeType &)); // 0x1403A1A90
void Scaleform::Alg::QuickSortSliced<Scaleform::Render::ArrayPaged<Scaleform::Render::Tessellator::TmpEdgeAAType,3,4>,bool (__cdecl*)(Scaleform::Render::Tessellator::TmpEdgeAAType const & __ptr64,Scaleform::Render::Tessellator::TmpEdgeAAType const & __ptr64)>(Scaleform::Render::ArrayPaged<Scaleform::Render::Tessellator::TmpEdgeAAType,3,4> & arr, unsigned long long start, unsigned long long end, bool(*less)(const Scaleform::Render::Tessellator::TmpEdgeAAType &, const Scaleform::Render::Tessellator::TmpEdgeAAType &)); // 0x1403A1ED0
void Scaleform::Alg::QuickSortSliced<Scaleform::Render::ArrayUnsafe<Scaleform::Render::Tessellator::MonoChainType * __ptr64>,bool (__cdecl*)(Scaleform::Render::Tessellator::MonoChainType const * __ptr64,Scaleform::Render::Tessellator::MonoChainType const * __ptr64)>(Scaleform::Render::ArrayUnsafe<Scaleform::Render::Tessellator::MonoChainType *> & arr, unsigned long long start, unsigned long long end, bool(*less)(const Scaleform::Render::Tessellator::MonoChainType *, const Scaleform::Render::Tessellator::MonoChainType *)); // 0x1403A23F0
void Scaleform::Alg::QuickSortSliced<Scaleform::Render::ArrayJagged<Scaleform::Render::Tessellator::TriangleType,4,16>::ArrayAdaptor,Scaleform::Render::Tessellator::CmpVer1>(Scaleform::Render::ArrayJagged<Scaleform::Render::Tessellator::TriangleType,4,16>::ArrayAdaptor & arr, unsigned long long start, unsigned long long end, Scaleform::Render::Tessellator::CmpVer1 less); // 0x1403A2670
void Scaleform::Alg::QuickSortSliced<Scaleform::Render::ArrayPaged<Scaleform::Render::TmpTextMeshEntry,6,4>,Scaleform::Render::TextMeshProvider::CmpEntries>(Scaleform::Render::ArrayPaged<Scaleform::Render::TmpTextMeshEntry,6,4> & arr, unsigned long long start, unsigned long long end, Scaleform::Render::TextMeshProvider::CmpEntries less); // 0x1403FD7F0
void Scaleform::Alg::QuickSortSliced<Scaleform::GFx::AS3::Instances::fl_display::MovieClip::FrameScript::Descr * __ptr64,bool (__cdecl*)(Scaleform::GFx::AS3::Instances::fl_display::MovieClip::FrameScript::Descr const & __ptr64,Scaleform::GFx::AS3::Instances::fl_display::MovieClip::FrameScript::Descr const & __ptr64)>(Scaleform::GFx::AS3::Instances::fl_display::MovieClip::FrameScript::Descr * & arr, unsigned long long start, unsigned long long end, bool(*less)(const Scaleform::GFx::AS3::Instances::fl_display::MovieClip::FrameScript::Descr &, const Scaleform::GFx::AS3::Instances::fl_display::MovieClip::FrameScript::Descr &)); // 0x140573440
void Scaleform::Alg::QuickSortSliced<Scaleform::Alg::ArrayAdaptor<char const * __ptr64>,Scaleform::Render::GL::StringLess>(Scaleform::Alg::ArrayAdaptor<char const *> & arr, unsigned long long start, unsigned long long end, Scaleform::Render::GL::StringLess less); // 0x1405F8A50
enum Scaleform::Alg::QuickSortSliced::__l2::<unnamed-enum-Threshold>
{
	Threshold = 9,
};
bool Scaleform::Alg::QuickSortSlicedSafe<Scaleform::ArrayDH<long const * __ptr64,2,Scaleform::ArrayDefaultPolicy>,Scaleform::GFx::AS3::VectorBase<long>::CompareValuePtr>(Scaleform::ArrayDH<long const *,2,Scaleform::ArrayDefaultPolicy> & arr, unsigned long long start, unsigned long long end, Scaleform::GFx::AS3::VectorBase<long>::CompareValuePtr less); // 0x140592CD0
bool Scaleform::Alg::QuickSortSlicedSafe<Scaleform::ArrayDH<unsigned long const * __ptr64,2,Scaleform::ArrayDefaultPolicy>,Scaleform::GFx::AS3::VectorBase<unsigned long>::CompareValuePtr>(Scaleform::ArrayDH<unsigned long const *,2,Scaleform::ArrayDefaultPolicy> & arr, unsigned long long start, unsigned long long end, Scaleform::GFx::AS3::VectorBase<unsigned long>::CompareValuePtr less); // 0x140592F90
bool Scaleform::Alg::QuickSortSlicedSafe<Scaleform::ArrayDH<double const * __ptr64,2,Scaleform::ArrayDefaultPolicy>,Scaleform::GFx::AS3::VectorBase<double>::CompareValuePtr>(Scaleform::ArrayDH<double const *,2,Scaleform::ArrayDefaultPolicy> & arr, unsigned long long start, unsigned long long end, Scaleform::GFx::AS3::VectorBase<double>::CompareValuePtr less); // 0x140593250
bool Scaleform::Alg::QuickSortSlicedSafe<Scaleform::ArrayDH<Scaleform::Ptr<Scaleform::GFx::ASStringNode> const * __ptr64,2,Scaleform::ArrayDefaultPolicy>,Scaleform::GFx::AS3::VectorBase<Scaleform::Ptr<Scaleform::GFx::ASStringNode> >::CompareValuePtr>(Scaleform::ArrayDH<Scaleform::Ptr<Scaleform::GFx::ASStringNode> const *,2,Scaleform::ArrayDefaultPolicy> & arr, unsigned long long start, unsigned long long end, Scaleform::GFx::AS3::VectorBase<Scaleform::Ptr<Scaleform::GFx::ASStringNode> >::CompareValuePtr less); // 0x140593510
bool Scaleform::Alg::QuickSortSlicedSafe<Scaleform::ArrayDH<Scaleform::GFx::AS3::Value const * __ptr64,2,Scaleform::ArrayDefaultPolicy>,Scaleform::GFx::AS3::VectorBase<Scaleform::GFx::AS3::Value>::CompareValuePtr>(Scaleform::ArrayDH<Scaleform::GFx::AS3::Value const *,2,Scaleform::ArrayDefaultPolicy> & arr, unsigned long long start, unsigned long long end, Scaleform::GFx::AS3::VectorBase<Scaleform::GFx::AS3::Value>::CompareValuePtr less); // 0x1405937D0
bool Scaleform::Alg::QuickSortSlicedSafe<Scaleform::ArrayDH<Scaleform::Pair<double,unsigned long>,2,Scaleform::ArrayDefaultPolicy>,Scaleform::GFx::AS3::Impl::CompareAsNumberInd>(Scaleform::ArrayDH<Scaleform::Pair<double,unsigned long>,2,Scaleform::ArrayDefaultPolicy> & arr, unsigned long long start, unsigned long long end, Scaleform::GFx::AS3::Impl::CompareAsNumberInd less); // 0x140593AC0
bool Scaleform::Alg::QuickSortSlicedSafe<Scaleform::ArrayDH<Scaleform::Pair<Scaleform::GFx::ASString,unsigned long>,2,Scaleform::ArrayDefaultPolicy>,Scaleform::GFx::AS3::Impl::CompareAsStringInd>(Scaleform::ArrayDH<Scaleform::Pair<Scaleform::GFx::ASString,unsigned long>,2,Scaleform::ArrayDefaultPolicy> & arr, unsigned long long start, unsigned long long end, Scaleform::GFx::AS3::Impl::CompareAsStringInd less); // 0x140593EA0
bool Scaleform::Alg::QuickSortSlicedSafe<Scaleform::ArrayDH<Scaleform::Pair<Scaleform::GFx::AS3::Value const * __ptr64,unsigned long>,2,Scaleform::ArrayDefaultPolicy>,Scaleform::GFx::AS3::Impl::CompareOn>(Scaleform::ArrayDH<Scaleform::Pair<Scaleform::GFx::AS3::Value const *,unsigned long>,2,Scaleform::ArrayDefaultPolicy> & arr, unsigned long long start, unsigned long long end, Scaleform::GFx::AS3::Impl::CompareOn less); // 0x1404E6E60
bool Scaleform::Alg::QuickSortSlicedSafe<Scaleform::ArrayDH<Scaleform::Pair<Scaleform::GFx::AS3::Value const * __ptr64,unsigned long>,2,Scaleform::ArrayDefaultPolicy>,Scaleform::GFx::AS3::Impl::CompareValuePtr>(Scaleform::ArrayDH<Scaleform::Pair<Scaleform::GFx::AS3::Value const *,unsigned long>,2,Scaleform::ArrayDefaultPolicy> & arr, unsigned long long start, unsigned long long end, Scaleform::GFx::AS3::Impl::CompareValuePtr less); // 0x1404E7210
bool Scaleform::Alg::QuickSortSlicedSafe<Scaleform::ArrayDH<Scaleform::GFx::AS3::Impl::Triple<double,Scaleform::GFx::AS3::Value const * __ptr64,unsigned long>,2,Scaleform::ArrayDefaultPolicy>,Scaleform::GFx::AS3::Impl::CompareAsNumber>(Scaleform::ArrayDH<Scaleform::GFx::AS3::Impl::Triple<double,Scaleform::GFx::AS3::Value const *,unsigned long>,2,Scaleform::ArrayDefaultPolicy> & arr, unsigned long long start, unsigned long long end, Scaleform::GFx::AS3::Impl::CompareAsNumber less); // 0x1404E75F0
bool Scaleform::Alg::QuickSortSlicedSafe<Scaleform::ArrayDH<Scaleform::GFx::AS3::Impl::Triple<Scaleform::GFx::ASString,Scaleform::GFx::AS3::Value const * __ptr64,unsigned long>,2,Scaleform::ArrayDefaultPolicy>,Scaleform::GFx::AS3::Impl::CompareAsString>(Scaleform::ArrayDH<Scaleform::GFx::AS3::Impl::Triple<Scaleform::GFx::ASString,Scaleform::GFx::AS3::Value const *,unsigned long>,2,Scaleform::ArrayDefaultPolicy> & arr, unsigned long long start, unsigned long long end, Scaleform::GFx::AS3::Impl::CompareAsString less); // 0x1404E7A00
enum Scaleform::Alg::QuickSortSlicedSafe::__l2::<unnamed-enum-Threshold>
{
	Threshold = 9,
};
void Scaleform::Alg::InsertionSortSliced<Scaleform::Render::ArrayPaged<Scaleform::Render::Tessellator::IntersectionType,4,4>,bool (__cdecl*)(Scaleform::Render::Tessellator::IntersectionType const & __ptr64,Scaleform::Render::Tessellator::IntersectionType const & __ptr64)>(Scaleform::Render::ArrayPaged<Scaleform::Render::Tessellator::IntersectionType,4,4> & arr, unsigned long long start, unsigned long long end, bool(*less)(const Scaleform::Render::Tessellator::IntersectionType &, const Scaleform::Render::Tessellator::IntersectionType &)); // 0x1403A14F0
void Scaleform::Alg::ReverseArray<Scaleform::ArrayDH<Scaleform::Ptr<Scaleform::GFx::ASStringNode>,2,Scaleform::ArrayDefaultPolicy> >(Scaleform::ArrayDH<Scaleform::Ptr<Scaleform::GFx::ASStringNode>,2,Scaleform::ArrayDefaultPolicy> & arr); // 0x140594490
void Scaleform::Alg::ReverseArray<Scaleform::ArrayDH<Scaleform::GFx::AS3::Value,2,Scaleform::ArrayDefaultPolicy> >(Scaleform::ArrayDH<Scaleform::GFx::AS3::Value,2,Scaleform::ArrayDefaultPolicy> & arr); // 0x1404E83A0
unsigned char Scaleform::Alg::UpperBit(unsigned long long val); // 0x140270F60
unsigned char Scaleform::Alg::LowerBit(unsigned long long val); // 0x14041E700
class Scaleform::Alg::MemUtil
{
public:
	static void * Copy(void *, const void *, unsigned long long);
	static void * Copy16(void *, const void *, unsigned long long);
	static void * Copy32(void *, const void *, unsigned long long);
	static void * Copy64(void *, const void *, unsigned long long);
	static void * Move(void *, const void *, unsigned long long);
	static void * Move16(void *, const void *, unsigned long long);
	static void * Move32(void *, const void *, unsigned long long);
	static void * Move64(void *, const void *, unsigned long long);
	static long Cmp(const void *, const void *, unsigned long long);
	static long Cmp16(const void *, const void *, unsigned long long);
	static long Cmp32(const void *, const void *, unsigned long long);
	static long Cmp64(const void *, const void *, unsigned long long);
	static void Set(void *, long, unsigned long long);
};
union Scaleform::Alg::ByteUtil::SwapOrder::__l2::<unnamed-type-u>
{
public:
	float p; // 0x0
	unsigned long v; // 0x0
};
double Scaleform::Alg::ByteUtil::SwapOrder(double p); // 0x140443AF0
union Scaleform::Alg::ByteUtil::SwapOrder::__l2::<unnamed-type-u>
{
public:
	double p; // 0x0
	unsigned long long v; // 0x0
};