#pragma once

void Scaleform::Render::ShaderHAL<Scaleform::Render::GL::ShaderManager,Scaleform::Render::GL::ShaderInterface>::DrawableCopyChannel(Scaleform::Render::Texture * * tex, const Scaleform::Render::Matrix2x4<float> * texgen, const Scaleform::Render::Matrix4x4<float> * cxmul); // 0x1405BE460
void Scaleform::Render::ShaderHAL<Scaleform::Render::GL::ShaderManager,Scaleform::Render::GL::ShaderInterface>::setBatchUnitSquareVertexStreamPerDraw(); // 0x14002E7C0
Scaleform::Render::ShaderHAL<Scaleform::Render::GL::ShaderManager,Scaleform::Render::GL::ShaderInterface>::ShaderHAL<Scaleform::Render::GL::ShaderManager,Scaleform::Render::GL::ShaderInterface>(Scaleform::Render::ThreadCommandQueue * commandQueue); // 0x1405BB5D0
bool Scaleform::Render::ShaderHAL<Scaleform::Render::GL::ShaderManager,Scaleform::Render::GL::ShaderInterface>::InitHAL(const Scaleform::Render::HALInitParams & params); // 0x1405BF5E0
bool Scaleform::Render::ShaderHAL<Scaleform::Render::GL::ShaderManager,Scaleform::Render::GL::ShaderInterface>::ShutdownHAL(); // 0x1405C32A0
bool Scaleform::Render::ShaderHAL<Scaleform::Render::GL::ShaderManager,Scaleform::Render::GL::ShaderInterface>::BeginScene(); // 0x1405BC7C0
bool Scaleform::Render::ShaderHAL<Scaleform::Render::GL::ShaderManager,Scaleform::Render::GL::ShaderInterface>::EndScene(); // 0x1405BEE70
unsigned long Scaleform::Render::ShaderHAL<Scaleform::Render::GL::ShaderManager,Scaleform::Render::GL::ShaderInterface>::GetMaximumBatchCount(Scaleform::Render::Primitive * prim); // 0x1405BF320
void Scaleform::Render::ShaderHAL<Scaleform::Render::GL::ShaderManager,Scaleform::Render::GL::ShaderInterface>::drawUncachedFilter(const Scaleform::Render::HAL::FilterStackEntry & e); // 0x1405C57E0
void Scaleform::Render::ShaderHAL<Scaleform::Render::GL::ShaderManager,Scaleform::Render::GL::ShaderInterface>::drawCachedFilter(Scaleform::Render::FilterPrimitive * primitive); // 0x1405C4B40
void Scaleform::Render::ShaderHAL<Scaleform::Render::GL::ShaderManager,Scaleform::Render::GL::ShaderInterface>::drawFilter(const Scaleform::Render::Matrix2x4<float> & mvp, const Scaleform::Render::Cxform & cx, const Scaleform::Render::Filter * filter, Scaleform::Ptr<Scaleform::Render::RenderTarget> * targets, unsigned long * shaders, unsigned long pass, unsigned long passCount, Scaleform::Render::VertexFormat * pvf); // 0x1405C5270
void Scaleform::Render::ShaderHAL<Scaleform::Render::GL::ShaderManager,Scaleform::Render::GL::ShaderInterface>::PushBlendMode(Scaleform::Render::BlendPrimitive * prim); // 0x1405C0BD0
void Scaleform::Render::ShaderHAL<Scaleform::Render::GL::ShaderManager,Scaleform::Render::GL::ShaderInterface>::PopBlendMode(); // 0x1405C0290
void Scaleform::Render::ShaderHAL<Scaleform::Render::GL::ShaderManager,Scaleform::Render::GL::ShaderInterface>::drawBlendPrimitive(Scaleform::Render::BlendPrimitive * prim, Scaleform::Render::Texture * blendSource, Scaleform::Render::Texture * blendDest, Scaleform::Render::Texture * blendAlpha); // 0x1405C4770
void Scaleform::Render::ShaderHAL<Scaleform::Render::GL::ShaderManager,Scaleform::Render::GL::ShaderInterface>::DrawProcessedPrimitive(Scaleform::Render::Primitive * pprimitive, Scaleform::Render::PrimitiveBatch * pstart, Scaleform::Render::PrimitiveBatch * pend); // 0x1405BE040
void Scaleform::Render::ShaderHAL<Scaleform::Render::GL::ShaderManager,Scaleform::Render::GL::ShaderInterface>::DrawProcessedComplexMeshes(Scaleform::Render::ComplexMesh * complexMesh, const Scaleform::Render::StrideArray<Scaleform::Render::MatrixPoolImpl::HMatrix> & matrices); // 0x1405BD690
void Scaleform::Render::ShaderHAL<Scaleform::Render::GL::ShaderManager,Scaleform::Render::GL::ShaderInterface>::DrawableCxform(Scaleform::Render::Texture * * tex, const Scaleform::Render::Matrix2x4<float> * texgen, const Scaleform::Render::Cxform * cx); // 0x1405BE6E0
void Scaleform::Render::ShaderHAL<Scaleform::Render::GL::ShaderManager,Scaleform::Render::GL::ShaderInterface>::DrawableCompare(Scaleform::Render::Texture * * tex, const Scaleform::Render::Matrix2x4<float> * texgen); // 0x1405BE380
void Scaleform::Render::ShaderHAL<Scaleform::Render::GL::ShaderManager,Scaleform::Render::GL::ShaderInterface>::DrawableMerge(Scaleform::Render::Texture * * tex, const Scaleform::Render::Matrix2x4<float> * texgen, const Scaleform::Render::Matrix4x4<float> * cxmul); // 0x1405BEAA0
void Scaleform::Render::ShaderHAL<Scaleform::Render::GL::ShaderManager,Scaleform::Render::GL::ShaderInterface>::DrawableCopyPixels(Scaleform::Render::Texture * * tex, const Scaleform::Render::Matrix2x4<float> * texgen, const Scaleform::Render::Matrix2x4<float> & mvp, bool mergeAlpha, bool destAlpha); // 0x1405BE470
void Scaleform::Render::ShaderHAL<Scaleform::Render::GL::ShaderManager,Scaleform::Render::GL::ShaderInterface>::DrawablePaletteMap(Scaleform::Render::Texture * * tex, const Scaleform::Render::Matrix2x4<float> * texgen, const Scaleform::Render::Matrix2x4<float> & mvp, unsigned long channelMask, const unsigned long * values); // 0x1405BEB90
void Scaleform::Render::ShaderHAL<Scaleform::Render::GL::ShaderManager,Scaleform::Render::GL::ShaderInterface>::DrawableCopyback(Scaleform::Render::Texture * source, const Scaleform::Render::Matrix2x4<float> & mvpOriginal, const Scaleform::Render::Matrix2x4<float> & texgen, unsigned long flagMask); // 0x1405BE570
void Scaleform::Render::ShaderHAL<Scaleform::Render::GL::ShaderManager,Scaleform::Render::GL::ShaderInterface>::drawScreenQuad(); // 0x1405C5780
void Scaleform::Render::ShaderHAL<Scaleform::Render::GL::ShaderManager,Scaleform::Render::GL::ShaderInterface>::drawMaskClearRectangles(const Scaleform::Render::Matrix2x4<float> * matrices, unsigned long long count); // 0x1405C53E0
void Scaleform::Render::ShaderHAL<Scaleform::Render::GL::ShaderManager,Scaleform::Render::GL::ShaderInterface>::ClearSolidRectangle(const Scaleform::Render::Rect<int> & r, Scaleform::Render::Color color, bool blend); // 0x1405BCA50
void Scaleform::Render::ShaderHAL<Scaleform::Render::GL::ShaderManager,Scaleform::Render::GL::ShaderInterface>::profilerDrawCacheablePrimArea(const Scaleform::Render::CacheablePrimitive * prim); // 0x1405C6670
void Scaleform::Render::ShaderHAL<Scaleform::Render::GL::ShaderManager,Scaleform::Render::GL::ShaderInterface>::profilerApplyUniform(Scaleform::Render::ProfilerUniform uniform, unsigned long components, float * values); // 0x1405C6600