#pragma once

enum `anonymous-namespace'::<unnamed-enum-HUD_COMICON_NUM_0>
{
	HUD_COMICON_NUM_0 = 0,
	HUD_COMICON_NUM_1 = 1,
	HUD_COMICON_NUM_2 = 2,
	HUD_COMICON_NUM_3 = 3,
	HUD_COMICON_NUM_4 = 4,
	HUD_COMICON_NUM_5 = 5,
	HUD_COMICON_NUM_6 = 6,
	HUD_COMICON_NUM_7 = 7,
	HUD_COMICON_NUM_8 = 8,
	HUD_COMICON_NUM_9 = 9,
	HUD_COMICON_KEY_U = 10,
	HUD_COMICON_KEY_RU = 11,
	HUD_COMICON_KEY_R = 12,
	HUD_COMICON_KEY_DR = 13,
	HUD_COMICON_KEY_D = 14,
	HUD_COMICON_KEY_DL = 15,
	HUD_COMICON_KEY_L = 16,
	HUD_COMICON_KEY_UL = 17,
	HUD_COMICON_BTN_HP = 18,
	HUD_COMICON_BTN_HK = 19,
	HUD_COMICON_BTN_LP = 20,
	HUD_COMICON_BTN_LK = 21,
	HUD_COMICON_BTN_NEUTRAL = 22,
};