#pragma once

enum `anonymous-namespace'::<unnamed-enum-YOUWIN_EFF_FLARE>
{
	YOUWIN_EFF_FLARE = 0,
	YOUWIN_EFF_LINE = 1,
	YOUWIN_EFF_SPARKS_00 = 2,
	YOUWIN_EFF_SPARKS_01 = 3,
	YOUWIN_EFF_SPARKS_02 = 4,
	YOUWIN_EFF_SPARKS_03 = 5,
	YOUWIN_EFF_SPARKS_04 = 6,
	YOUWIN_EFF_SPARKS_S_00 = 7,
	YOUWIN_EFF_SPARKS_S_01 = 8,
	YOUWIN_EFF_SPARKS_S_02 = 9,
	YOUWIN_EFF_SPARKS_S_03 = 10,
	YOUWIN_EFF_SPARKS_S_04 = 11,
	YOUWIN_EFF_SPARKS_S_05 = 12,
	YOUWIN_EFF_SPARKS_S_06 = 13,
	YOUWIN_YOU_WIN = 14,
	YOUWIN_EFF_YOU_WIN_BURST = 15,
};