#pragma once

enum EffectParticleTypeVertexShader
{
	EFFECT_VS_PARTICLE_TYPE_INSTANCING = 0,
	ALL_EFFECT_VS_PARTICLE_TYPE = 1,
};
enum EffectFallOffTypeVertexShader
{
	EFFECT_VS_NO_OPACITY_FALLOFF = 0,
	EFFECT_VS_IN_OPACITY_FALLOFF = 1,
	EFFECT_VS_OUT_OPACITY_FALLOFF = 2,
	ALL_EFFECT_VS_OPACITY_FALLOFF_TYPE = 3,
};
enum EffectLightingVertexShader
{
	EFFECT_VS_NOT_LIGHTING = 0,
	EFFECT_VS_USE_FAKE_LIGHTING = 1,
	ALL_EFFECT_VS_LIGHTING_TYPE = 2,
};
enum EffectBlendProjectionVertexShader
{
	EFFECT_VS_NOT_USE_BLEND_PROJECTION = 0,
	EFFECT_VS_USE_BLEND_PROJECTION = 1,
	ALL_EFFECT_VS_BLEND_PROJECTION_TYPE = 2,
};
enum EffectCompareDepthPixelShader
{
	EFFECT_PS_NO_COMPARE_DEPTH = 0,
	EFFECT_PS_COMPARE_DEPTH_TO_CHARACTER = 1,
	EFFECT_PS_COMPARE_DEPTH_TO_STAGE = 2,
	EFFECT_PS_COMPARE_DEPTH_TO_CHARACTER_STAGE = 3,
	EFFECT_PS_COMPARE_DEPTH_TO_CHARACTER1 = 4,
	EFFECT_PS_COMPARE_DEPTH_TO_CHARACTER2 = 5,
	ALL_EFFECT_PS_COMPARE_DEPTH = 6,
};
enum EffectTexturePixelShader
{
	EFFECT_PS_TEXTURE_DEFAULT = 0,
	EFFECT_PS_TEXTURE_DISTORTION = 1,
	EFFECT_PS_BACKGROUND_DISTORTION = 2,
	EFFECT_PS_BACKGROUND_DISTORTION_AND_TEXTURE = 3,
	EFFECT_PS_BLUR = 4,
	ALL_EFFECT_PS_TEXTURE = 5,
};
enum EffectMultiTextureBlend
{
	EFFECT_PS_NO_MULTI_TEXTURE = 0,
	EFFECT_PS_MULTI_TEXTURE_ALPHA_BLEND = 1,
	EFFECT_PS_MULTI_TEXTURE_ADD_BLEND = 2,
	EFFECT_PS_MULTI_TEXTURE_SUB_BLEND = 3,
	EFFECT_PS_MULTI_TEXTURE_MULTIPLY_BLEND = 4,
	ALL_EFFECT_PS_MULTI_TEXTURE_BLEND = 5,
};
enum EffectSeparateAlphaTexture
{
	EFFECT_PS_NO_SEPARATE = 0,
	EFFECT_PS_SEPARATE_ALPHA = 1,
	ALL_EFFECT_PS_SEPARATE_ALPHA_TEXTURE = 2,
};
enum EffectFog
{
	EFFECT_PS_DISUSE_FOG = 0,
	EFFECT_PS_USE_FOG = 1,
	ALL_EFFECT_PS_FOG = 2,
};
enum EffectBloom
{
	EFFECT_PS_DISUSE_BLOOM = 0,
	EFFECT_PS_USE_BLOOM = 1,
	ALL_EFFECT_PS_BLOOM = 2,
};
enum <unnamed-enum-OGL_CS_SHADER_EFFECT_EMIT_BUFFER_AXIS_X>
{
	OGL_CS_SHADER_EFFECT_EMIT_BUFFER_AXIS_X = 0,
	OGL_CS_SHADER_EFFECT_EMIT_BUFFER_AXIS_Y = 1,
	OGL_CS_SHADER_EFFECT_EMIT_BUFFER_AXIS_Z = 2,
	OGL_CS_SHADER_EFFECT_EMIT_BUFFER_REVERSE_AXIS_X = 3,
	OGL_CS_SHADER_EFFECT_EMIT_BUFFER_REVERSE_AXIS_Y = 4,
	OGL_CS_SHADER_EFFECT_EMIT_BUFFER_REVERSE_AXIS_Z = 5,
	OGL_CS_SHADER_EFFECT_INIT_BUFFER = 6,
	OGL_CS_SHADER_EFFECT_UPDATE_BUFFER = 7,
	OGL_CS_SHADER_EFFECT_UPDATE_BUFFER_REVERSE = 8,
	OGL_CS_SHADER_EFFECT_COUNT_DISPATCH_BUFFER = 9,
	OGL_CS_SHADER_EFFECT_COUNT_DRAW_BUFFER = 10,
	OGL_CS_SHADER_EFFECT_CLEAR_BUFFER = 11,
	OGL_RENDER_ORIGINAL_COMPUTE_SHADER_EFFECT = 12,
};
enum <unnamed-enum-OGL_CS_SHADER_EFFECT_COMBINE_BLEND_BUFFER>
{
	OGL_CS_SHADER_EFFECT_COMBINE_BLEND_BUFFER = 0,
	OGL_PS_SHADER_EFFECT_COMBINE_BLEND_BUFFER = 1,
	OGL_PS_SHADER_EFFECT_COMBINE_UPSAMPLE_BLEND_BUFFER = 2,
	OGL_PS_SHADER_EFFECT_COMBINE_MIRROR_UPSAMPLE_BLEND_BUFFER = 3,
	OGL_PS_SHADER_EFFECT_COMBINE_UPSAMPLE_BLEND_BUFFER_NEO = 4,
	OGL_PS_SHADER_EFFECT_COMBINE_MIRROR_UPSAMPLE_BLEND_BUFFER_NEO = 5,
	OGL_RENDER_ORIGINAL_POST_PROCESS_SHADER_EFFECT = 6,
};