#pragma once

enum DamageSettingUtil::<unnamed-enum-DEFAULT_DOWN_FRAME>
{
	DEFAULT_DOWN_FRAME = 10,
	JUST_GUARD_BONUS_FRAME = 0,
	STUN_STATE_LOOP_FRAME = 180,
	JUST_GUARD_BONUS_GAUGE = 10,
	GUARD_CANCEL_EVADE_STOP = 4,
	GUARD_CANCEL_BLOW_AIR_STOP = 4,
	GUARD_CRASH_HIT_STOP = 20,
	STUN_RECOVER_RAPID_FRAME = 5,
	THROW_MUTEKI_FRAME = 11,
	THROW_INPUT_DISABLE_FRAME = 5,
	GUARD_POINT_HIT_STOP_ATK = 12,
	GUARD_POINT_HIT_STOP_PSV = 12,
	ATEMI_HIT_STOP_ATK = 14,
	ATEMI_HIT_STOP_PSV = 12,
};