#pragma once

enum `anonymous-namespace'::<unnamed-enum-DRAW_EFF_LINE>
{
	DRAW_EFF_LINE = 0,
	DRAW_EFF_SPARKS_00 = 1,
	DRAW_EFF_SPARKS_01 = 2,
	DRAW_EFF_SPARKS_02 = 3,
	DRAW_EFF_SPARKS_03 = 4,
	DRAW_EFF_SPARKS_04 = 5,
	DRAW_EFF_SPARKS_05 = 6,
	DRAW_EFF_SPARKS_06 = 7,
	DRAW_EFF_DRAW_BURST = 8,
	DRAW_DRAW = 9,
};