#pragma once

enum `anonymous-namespace'::<unnamed-enum-PERFECT_EFF_FLARE>
{
	PERFECT_EFF_FLARE = 0,
	PERFECT_EFF_LINE = 1,
	PERFECT_EFF_SPARKS_00 = 2,
	PERFECT_EFF_SPARKS_01 = 3,
	PERFECT_EFF_SPARKS_02 = 4,
	PERFECT_EFF_SPARKS_04 = 5,
	PERFECT_EFF_SPARKS_03 = 6,
	PERFECT_EFF_SPARKS_S_00 = 7,
	PERFECT_EFF_SPARKS_S_01 = 8,
	PERFECT_EFF_SPARKS_S_02 = 9,
	PERFECT_EFF_SPARKS_S_05 = 10,
	PERFECT_EFF_SPARKS_S_03 = 11,
	PERFECT_EFF_SPARKS_S_06 = 12,
	PERFECT_EFF_SPARKS_S_04 = 13,
	PERFECT_PERFECT = 14,
	PERFECT_EFF_PERFECT_BURST = 15,
};