#pragma once

enum `anonymous-namespace'::<unnamed-enum-YOULOSE_EFF_LINE>
{
	YOULOSE_EFF_LINE = 0,
	YOULOSE_EFF_SPARKS_00 = 1,
	YOULOSE_EFF_SPARKS_01 = 2,
	YOULOSE_EFF_SPARKS_02 = 3,
	YOULOSE_EFF_SPARKS_05 = 4,
	YOULOSE_EFF_SPARKS_06 = 5,
	YOULOSE_EFF_SPARKS_03 = 6,
	YOULOSE_EFF_SPARKS_04 = 7,
	YOULOSE_EFF_YOU_LOSE_BURST = 8,
	YOULOSE_YOU_LOSE = 9,
};