#pragma once

void easing(float & outParam, float frame, float aniFrame1, float p1, Tween::EasingType type1, float aniFrame2, float p2, Tween::EasingType type2, float aniFrame3, float p3); // 0x1400A1850
void easing(float & outParam, float frame, float aniFrame1, float p1, Tween::EasingType type1, float aniFrame2, float p2, Tween::EasingType type2, float aniFrame3, float p3, Tween::EasingType type3, float aniFrame4, float p4); // 0x1400A18F0
void easing(float & outParam, float frame, float aniFrame1, float p1, Tween::EasingType type1, float aniFrame2, float p2, Tween::EasingType type2, float aniFrame3, float p3, Tween::EasingType type3, float aniFrame4, float p4, Tween::EasingType type4, float aniFrame5, float p5); // 0x1400A19D0
void easing(float & outParam, float frame, float aniFrame1, float p1, Tween::EasingType type1, float aniFrame2, float p2, Tween::EasingType type2, float aniFrame3, float p3, Tween::EasingType type3, float aniFrame4, float p4, Tween::EasingType type4, float aniFrame5, float p5, Tween::EasingType type5, float aniFrame6, float p6); // 0x1400A1AF0
void easing(float & outParam, float frame, float aniFrame1, float p1, Tween::EasingType type1, float aniFrame2, float p2, Tween::EasingType type2, float aniFrame3, float p3, Tween::EasingType type3, float aniFrame4, float p4, Tween::EasingType type4, float aniFrame5, float p5, Tween::EasingType type5, float aniFrame6, float p6, Tween::EasingType type6, float aniFrame7, float p7, Tween::EasingType type7, float aniFrame8, float p8); // 0x1400A47B0
void easing(float & outParams1, float & outParams2, float frame, float aniFrame1, float p11, float p12, Tween::EasingType type1, float aniFrame2, float p21, float p22); // 0x1400A1C30
void easing(float & outParams1, float & outParams2, float frame, float aniFrame1, float p11, float p12, Tween::EasingType type1, float aniFrame2, float p21, float p22, Tween::EasingType type2, float aniFrame3, float p31, float p32); // 0x1400A1CF0
void easing(float & outParams1, float & outParams2, float frame, float aniFrame1, float p11, float p12, Tween::EasingType type1, float aniFrame2, float p21, float p22, Tween::EasingType type2, float aniFrame3, float p31, float p32, Tween::EasingType type3, float aniFrame4, float p41, float p42); // 0x1400A1E20
void easing(float & outParams1, float & outParams2, float frame, float aniFrame1, float p11, float p12, Tween::EasingType type1, float aniFrame2, float p21, float p22, Tween::EasingType type2, float aniFrame3, float p31, float p32, Tween::EasingType type3, float aniFrame4, float p41, float p42, Tween::EasingType type4, float aniFrame5, float p51, float p52); // 0x1400A4980
void easing(float & outParams1, float & outParams2, float frame, float aniFrame1, float p11, float p12, Tween::EasingType type1, float aniFrame2, float p21, float p22, Tween::EasingType type2, float aniFrame3, float p31, float p32, Tween::EasingType type3, float aniFrame4, float p41, float p42, Tween::EasingType type4, float aniFrame5, float p51, float p52, Tween::EasingType type5, float aniFrame6, float p61, float p62); // 0x1400A1FC0
void easing(float & outParams1, float & outParams2, float frame, float aniFrame1, float p11, float p12, Tween::EasingType type1, float aniFrame2, float p21, float p22, Tween::EasingType type2, float aniFrame3, float p31, float p32, Tween::EasingType type3, float aniFrame4, float p41, float p42, Tween::EasingType type4, float aniFrame5, float p51, float p52, Tween::EasingType type5, float aniFrame6, float p61, float p62, Tween::EasingType type6, float aniFrame7, float p71, float p72); // 0x1400A2210
void easing(float & outParams1, float & outParams2, float frame, float aniFrame1, float p11, float p12, Tween::EasingType type1, float aniFrame2, float p21, float p22, Tween::EasingType type2, float aniFrame3, float p31, float p32, Tween::EasingType type3, float aniFrame4, float p41, float p42, Tween::EasingType type4, float aniFrame5, float p51, float p52, Tween::EasingType type5, float aniFrame6, float p61, float p62, Tween::EasingType type6, float aniFrame7, float p71, float p72, Tween::EasingType type7, float aniFrame8, float p81, float p82); // 0x1400A2910
void easing(float & outParams1, float & outParams2, float frame, float aniFrame1, float p11, float p12, Tween::EasingType type1, float aniFrame2, float p21, float p22, Tween::EasingType type2, float aniFrame3, float p31, float p32, Tween::EasingType type3, float aniFrame4, float p41, float p42, Tween::EasingType type4, float aniFrame5, float p51, float p52, Tween::EasingType type5, float aniFrame6, float p61, float p62, Tween::EasingType type6, float aniFrame7, float p71, float p72, Tween::EasingType type7, float aniFrame8, float p81, float p82, Tween::EasingType type8, float aniFrame9, float p91, float p92); // 0x1400A24D0