#pragma once

enum MATCHING_WORLD_INDEX
{
	MATCHING_WORLD_INDEX_RANK = 0,
	MATCHING_WORLD_INDEX_FREE1ON1 = 1,
	MATCHING_WORLD_INDEX_FREE3ON3 = 2,
	MATCHING_WORLD_INDEX_FREEPARTY = 3,
	MATCHING_WORLD_INDEX_DUMMY1 = 4,
	MATCHING_WORLD_INDEX_RANK_PRISON = 5,
	MATCHING_WORLD_INDEX_DUMMY2 = 6,
	MATCHING_WORLD_INDEX_TRAINING = 7,
	MATCHING_WORLD_INDEX_MAX = 8,
};
enum <unnamed-enum-SEND_FLAG_NONE>
{
	SEND_FLAG_NONE = 0,
	SEND_FLAG_ALL = 1,
	SEND_FLAG_ADDRLIST = 2,
	SEND_FLAG_HOST = 3,
	SEND_FLAG_HOST_SIG = 4,
};
enum changeDataType
{
	FLAG_DATA = 1,
	INTERNAL_DATA = 2,
	EXTERNAL_DATA = 4,
};
struct ChangeRoomFlagData
{
};
struct ChangeRoomInternalData
{
};
struct ChangeRoomExternalData
{
};
struct ChangeRoomDataList
{
	changeDataType dataType; // 0x0
	ChangeRoomFlagData changeRoomFlagData; // 0x4
	ChangeRoomInternalData changeRoomInternalData; // 0x5
	ChangeRoomExternalData changeRoomExternalData; // 0x6
};
enum NETWORK_ERROR
{
	NETWORK_ERROR_ROOM_FULL = 0,
	NETWORK_ERROR_NO_SUCH_ROOM = 1,
	NETWORK_ERROR_NO_SUCH_ROOM_INSTANCE = 2,
	NETWORK_ERROR_NO_ROOM_NOT_FOUND = 3,
	NETWORK_ERROR_TIMEOUT = 4,
	NETWORK_ERROR_ROOM_DESTROYED = 5,
	NET_ERROR_RESOLVER_ENODNS = 6,
	NET_ERROR_EINACTIVEDISABLED = 7,
	NETWORK_ERROR_SESSION_DESTROYED = 8,
	NETWORK_ERROR_TERMINATED_BY_MYSELF = 9,
	NETWORK_ERROR_KEEPALIVE_TIMEOUT = 10,
	NETWORK_ERROR_SIGNED_OUT = 11,
};